/**
 * Webpack Module #19305
 * @exports BootAction
 * @esmodule
 */
// (e/*module*/, t/*exports*/, n/*__require*/) =>
{
  ;("use strict")
  ;(Object.defineProperty(t, "__esModule", { value: !0 }), (t.BootAction = void 0))
  var i = n(70655),
    r = n(73802),
    o = n(86178),
    a = n(84194),
    s = n(86125),
    u = n(44656),
    l = n(48616),
    c = i.__importStar(n(90505)),
    d = n(86700),
    h = (function (e) {
      function t() {
        return (null !== e && e.apply(this, arguments)) || this
      }
      return (
        i.__extends(t, e),
        (t.prototype.execute = function () {
          var e, t, n
          return i.__awaiter(this, void 0, void 0, function () {
            var d,
              h,
              p,
              f,
              _,
              g = this
            return i.__generator(this, function (i) {
              switch (i.label) {
                case 0:
                  return (
                    (d = {
                      id: "159047249520140",
                      sentry: {
                        project: "state-io",
                        dsn: "https://92ce172250c24cfb9b5a38a6e7865ff7@o1362967.ingest.sentry.io/6660018",
                        org: "diesel-g6",
                        authToken:
                          "fedd38ffec1248c0868dc1ea11dda9ab65be6bdd21bb4ecc8faae92d7c1837a8",
                        release: "0.0.63",
                      },
                      audio: {
                        sounds: {
                          src: [
                            "assets/sounds/track.mp3",
                            "assets/sounds/track.m4a",
                            "assets/sounds/track.ac3",
                            "assets/sounds/track.ogg",
                          ],
                          sprite: { click_ui: [0, 500] },
                        },
                      },
                      i18n: {
                        "ui-store-building": {
                          default: "BUILDING",
                          localizations: {
                            ru_RU: "ЗДАНИЯ",
                            es_ES: "EDIFICIO",
                            es_LA: "EDIFICIO",
                            pt_PT: "EDIFÍCIO",
                            pt_BR: "EDIFÍCIO",
                            zh_CN: "建筑",
                            fr_FR: "BÂTIMENT",
                            de_DE: "GEBÄUDE",
                            zh_TW: "建築",
                            ja_JP: "ビル",
                            ko_KR: "몸체",
                            it_IT: "EDIFICIO",
                            pl_PL: "BUDYNEK",
                            tr_TR: "ÜS",
                            th_TH: "ตึก",
                            hi_IN: "बिल्डिंग",
                            vi_VN: "TÒA NHÀ",
                            id_ID: "BANGUNAN",
                            ms_MY: "BANGUNAN",
                          },
                        },
                        "ui-store-fighter": {
                          default: "FIGHTER",
                          localizations: {
                            ru_RU: "БОЙЦЫ",
                            es_ES: "LUCHADOR",
                            es_LA: "LUCHADOR",
                            pt_PT: "SOLDADO",
                            pt_BR: "LUTADOR",
                            zh_CN: "斗士",
                            fr_FR: "GUERRIER",
                            de_DE: "KÄMPFER",
                            zh_TW: "戰士",
                            ja_JP: "ファイター",
                            ko_KR: "공격수",
                            it_IT: "SOLDATO",
                            pl_PL: "WOJAK",
                            tr_TR: "SAVAŞÇI",
                            th_TH: "นักสู้",
                            hi_IN: "फाइटर",
                            vi_VN: "CHIẾN SỸ",
                            id_ID: "TENTARA",
                            ms_MY: "PEJUANG",
                          },
                        },
                        share: {
                          default: "Share",
                          localizations: {
                            ru_RU: "Поделиться",
                            es_ES: "Compartir",
                            es_LA: "Compartir",
                            pt_PT: "Partilhar",
                            pt_BR: "Compartilhar",
                            fr_FR: "Partager",
                            de_DE: "Teilen",
                            zh_CN: "分享",
                            zh_TW: "分享",
                            ja_JP: "シェア",
                            ko_KR: "공유",
                            it_IT: "Condividi",
                            pl_PL: "Udostępnij",
                            tr_TR: "Paylaş",
                            th_TH: "แชร์",
                            hi_IN: "शेयर करें",
                            vi_VN: "Chia sẻ",
                            id_ID: "Bagikan",
                            ms_MY: "Kongsi",
                          },
                        },
                        "ui-store-color": {
                          default: "COLOR",
                          localizations: {
                            ru_RU: "ЦВЕТ",
                            es_ES: "COLOR",
                            es_LA: "COLOR",
                            pt_PT: "COR",
                            pt_BR: "COR",
                            zh_CN: "颜色",
                            fr_FR: "COULEUR",
                            de_DE: "FARBE",
                            zh_TW: "顏色",
                            ja_JP: "色",
                            ko_KR: "스킨",
                            it_IT: "COLORE",
                            pl_PL: "KOLOR",
                            tr_TR: "RENK",
                            th_TH: "สี",
                            hi_IN: "रंग",
                            vi_VN: "MÀU SẮC",
                            id_ID: "WARNA",
                            ms_MY: "WARNA",
                          },
                        },
                        "ui-menu-tap_to_play": {
                          default: "TAP TO PLAY",
                          localizations: {
                            ru_RU: "ИГРАТЬ",
                            es_ES: "TOCA PARA JUGAR",
                            es_LA: "TOCA PARA JUGAR",
                            pt_PT: "TOQUE PARA JOGAR",
                            pt_BR: "TOCA PARA JOGAR",
                            zh_CN: "点击开始",
                            fr_FR: "TAPER POUR JOUER",
                            de_DE: "ZUM SPIELEN TIPPEN",
                            zh_TW: "點擊遊玩",
                            ja_JP: "タップしてプレイ",
                            ko_KR: "탭해서 플레이하세요",
                            it_IT: "TOCCA PER GIOCARE",
                            pl_PL: "DOTKNIJ, ABY ZAGRAĆ",
                            tr_TR: "OYNAMAK İÇİN DOKUN",
                            th_TH: "แตะเพื่อเล่น",
                            hi_IN: "खेलने के लिए टैप करें",
                            vi_VN: "CHẠM ĐỂ CHƠI",
                            id_ID: "KETUK UNTUK BERMAIN",
                            ms_MY: "KETIK UNTUK BERMAIN",
                          },
                        },
                        "ui-settings-settings": {
                          default: "SETTINGS",
                          localizations: {
                            ru_RU: "НАСТРОЙКИ",
                            es_ES: "CONFIGURACIÓN",
                            es_LA: "AJUSTES",
                            pt_PT: "CONFIGURAÇÕES",
                            pt_BR: "DEFINIÇÕES",
                            zh_CN: "设置",
                            fr_FR: "PARAMÈTRES",
                            de_DE: "EINSTELLUNGEN",
                            zh_TW: "設置",
                            ja_JP: "設定",
                            ko_KR: "설정",
                            it_IT: "IMPOSTAZIONI",
                            pl_PL: "USTAWIENIA",
                            tr_TR: "AYARLAR",
                            th_TH: "การตั้งค่า",
                            hi_IN: "सेटिंग्स",
                            vi_VN: "CÀI ĐẶT",
                            id_ID: "PENGATURAN",
                            ms_MY: "TETAPAN",
                          },
                        },
                        "ui-settings-rate_us": {
                          default: "RATE US",
                          localizations: {
                            ru_RU: "ОЦЕНИТЕ НАС",
                            es_ES: "PUNTÚANOS",
                            es_LA: "CALIFÍCANOS",
                            pt_PT: "AVALIE-NOS",
                            pt_BR: "AVALIA-NOS",
                            zh_CN: "给我们打分",
                            fr_FR: "ÉVALUATION",
                            de_DE: "BEWERTEN",
                            zh_TW: "評價我們",
                            ja_JP: "ゲームを評価する",
                            ko_KR: "평가해주세요",
                            it_IT: "VALUTACI",
                            pl_PL: "OCEŃ NAS",
                            tr_TR: "PUANLA",
                            th_TH: "ให้คะแนน",
                            hi_IN: "रेटिंग करें",
                            vi_VN: "Đ.GIÁ",
                            id_ID: "BERI NILAI",
                            ms_MY: "NILAIKAN",
                          },
                        },
                        "ui-win-win_label": {
                          default: "YOU WON",
                          localizations: {
                            ru_RU: "ПОБЕДА",
                            es_ES: "HAS GANADO",
                            es_LA: "GANASTE",
                            pt_PT: "VOCÊ VENCEU",
                            pt_BR: "GANHASTE",
                            zh_CN: "你赢了",
                            fr_FR: "VOUS AVEZ GAGNÉ",
                            de_DE: "GEWONNEN",
                            zh_TW: "您獲勝了",
                            ja_JP: "勝ち",
                            ko_KR: "승리했습니다",
                            it_IT: "HAI VINTO",
                            pl_PL: "WYGRYWASZ",
                            tr_TR: "KAZANDIN",
                            th_TH: "คุณชนะ",
                            hi_IN: "आप जीत गए",
                            vi_VN: "BẠN ĐÃ THẮNG",
                            id_ID: "KAMU MENANG",
                            ms_MY: "ANDA MENANG",
                          },
                        },
                        "ui-win-reward_label": {
                          default: "YOUR REWARD",
                          localizations: {
                            ru_RU: "НАГРАДА",
                            es_ES: "TU RECOMPENSA",
                            es_LA: "TU RECOMPENSA",
                            pt_PT: "SUA RECOMPENSA",
                            pt_BR: "A TUA RECOMPENSA",
                            zh_CN: "你的奖励",
                            fr_FR: "VOTRE RÉCOMPENSE",
                            de_DE: "DEINE BELOHNUNG",
                            zh_TW: "您的獎勵",
                            ja_JP: "報酬",
                            ko_KR: "보상",
                            it_IT: "IL TUO PREMIO",
                            pl_PL: "TWOJA NAGRODA",
                            tr_TR: "ÖDÜLÜN",
                            th_TH: "รางวัลของคุณ",
                            hi_IN: "आपका इनाम",
                            vi_VN: "PHẦN THƯỞNG CỦA BẠN",
                            id_ID: "HADIAHMU",
                            ms_MY: "GANJARAN ANDA",
                          },
                        },
                        "ui-lose-lose_label": {
                          default: "YOU LOSE",
                          localizations: {
                            ru_RU: "ПОРАЖЕНИЕ",
                            es_ES: "HAS PERDIDO",
                            es_LA: "PERDISTE",
                            pt_PT: "VOCÊ PERDEU",
                            pt_BR: "PERDES",
                            zh_CN: "你输了",
                            fr_FR: "VOUS PERDEZ",
                            de_DE: "VERLOREN",
                            zh_TW: "您落敗了",
                            ja_JP: "失う",
                            ko_KR: "패배했습니다",
                            it_IT: "HAI PERSO",
                            pl_PL: "PRZEGRYWASZ",
                            tr_TR: "KAYBETTİN",
                            th_TH: "คุณแพ้",
                            hi_IN: "आप हार रहे हैं",
                            vi_VN: "BẠN THUA",
                            id_ID: "KAMU KALAH",
                            ms_MY: "ANDA KALAH",
                          },
                        },
                        "ui-lose-lost_label": {
                          default: "YOU LOST",
                          localizations: {
                            ru_RU: "ВЫ ПОТЕРЯЕТЕ",
                            es_ES: "HAS PERDIDO",
                            es_LA: "HAS PERDIDO",
                            pt_PT: "VOCÊ PERDEU",
                            pt_BR: "PERDESTE",
                            zh_CN: "你输了",
                            fr_FR: "VOUS AVEZ PERDU",
                            de_DE: "DU HAST VERLOREN",
                            zh_TW: "您落敗了",
                            ja_JP: "負け",
                            ko_KR: "패배했습니다",
                            it_IT: "PERDI",
                            pl_PL: "STRATA",
                            tr_TR: "KAYBETTİN",
                            th_TH: "คุณแพ้",
                            hi_IN: "आप हार गए",
                            vi_VN: "BẠN ĐÃ THUA",
                            id_ID: "KAMU KEHILANGAN",
                            ms_MY: "ANDA HILANG",
                          },
                        },
                        "ui-common-no_thanks_button": {
                          default: "NO, THANKS",
                          localizations: {
                            ru_RU: "НЕТ, СПАСИБО",
                            es_ES: "NO, GRACIAS",
                            es_LA: "NO, GRACIAS",
                            pt_PT: "NÃO, OBRIGADO(A)",
                            pt_BR: "NÃO, OBRIGADO",
                            zh_CN: "不，谢谢",
                            fr_FR: "NON MERCI",
                            de_DE: "NEIN DANKE",
                            zh_TW: "不用了",
                            ja_JP: "いいえ",
                            ko_KR: "괜찮아요",
                            it_IT: "NO, GRAZIE",
                            pl_PL: "NIE, DZIĘKI",
                            tr_TR: "HAYIR, TEŞEKKÜRLER",
                            th_TH: "ไม่เป็นไร ขอบคุณ",
                            hi_IN: "नहीं धन्यवाद",
                            vi_VN: "KHÔNG, CẢM ƠN",
                            id_ID: "TIDAK TERIMA KASIH",
                            ms_MY: "TIDAK, TERIMA KASIH",
                          },
                        },
                        "ui-exit-exit_label": {
                          default: "EXIT",
                          localizations: {
                            ru_RU: "ВЫХОД",
                            es_ES: "SALIR",
                            es_LA: "SALIR",
                            pt_PT: "SAIR",
                            pt_BR: "SAIR",
                            zh_CN: "退出",
                            fr_FR: "QUITTER",
                            de_DE: "VERLASSEN",
                            zh_TW: "退出遊戲嗎？",
                            ja_JP: "退出する",
                            ko_KR: "나가기",
                            it_IT: "ESCI",
                            pl_PL: "WYJŚCIE",
                            tr_TR: "ÇIKIŞ",
                            th_TH: "ออก",
                            hi_IN: "एग्जिट",
                            vi_VN: "THOÁT",
                            id_ID: "KELUAR",
                            ms_MY: "KELUAR",
                          },
                        },
                        "ui-exit-description": {
                          default: "Leave the game?",
                          localizations: {
                            ru_RU: "Вы точно хотите выйти?",
                            es_ES: "¿Salir del juego?",
                            es_LA: "¿Salir del juego?",
                            pt_PT: "Sair do jogo?",
                            pt_BR: "Deixar o jogo?",
                            zh_CN: "离开游戏？",
                            fr_FR: "Quitter le jeu ?",
                            de_DE: "Spiel verlassen?",
                            zh_TW: "圓點大亂鬥",
                            ja_JP: "ゲームから退出しますか？",
                            ko_KR: "게임을 나가시겠습니까?",
                            it_IT: "Vuoi uscire dal gioco?",
                            pl_PL: "Opuścić grę?",
                            tr_TR: "Oyundan çıkılsın mı?",
                            th_TH: "ออกจากเกมหรือไม่?",
                            hi_IN: "क्या गेम छोड़ें?",
                            vi_VN: "Thoát khỏi trò chơi?",
                            id_ID: "Keluar dari game?",
                            ms_MY: "Tinggalkan permainan?",
                          },
                        },
                        "ui-rate-description": {
                          default: "Enjoy our game?",
                          localizations: {
                            ru_RU: "Нравится наша игра?",
                            es_ES: "¿Te gusta el juego?",
                            es_LA: "¿Te gusta el juego?",
                            pt_PT: "Curtiu o jogo?",
                            pt_BR: "Gostou do jogo?",
                            zh_CN: "你觉得游戏怎么样？",
                            fr_FR: "Appréciez-vous le jeu ?",
                            de_DE: "Gefällt dir das Spiel?",
                            zh_TW: "你喜歡本遊戲嗎？",
                            ja_JP: "ゲームはどの程度気に入っていただけましたか？",
                            ko_KR: "게임을 얼마나 좋아하세요?",
                            it_IT: "Ti piace il gioco?",
                            pl_PL: "Podoba ci się nasza gra?",
                            tr_TR: "Oyunu beğendin mi?",
                            th_TH: "ชอบเกมนี้แค่ไหน",
                            hi_IN: "क्या क्लैश ऑफ़ डॉट्स अच्छा लगा?",
                            vi_VN: "Bạn có thích trò chơi không?",
                            id_ID: "Kamu suka game ini?",
                            ms_MY: "Bagaimana anda suka permainan?",
                          },
                        },
                        "ui-rate-rate": {
                          default: "RATE",
                          localizations: {
                            ru_RU: "ОЦЕНИТЬ",
                            es_ES: "PUNTÚA",
                            es_LA: "CALIFÍCANOS",
                            pt_PT: "AVALIE",
                            pt_BR: "AVALIA",
                            zh_CN: "打分",
                            fr_FR: "NOTER",
                            de_DE: "BEWERT",
                            zh_TW: "評分",
                            ja_JP: "評価する",
                            ko_KR: "평가하기",
                            it_IT: "VALUTA",
                            pl_PL: "OCEŃ",
                            tr_TR: "PUANLA",
                            th_TH: "จัดอันดับ",
                            hi_IN: "रेटिंग",
                            vi_VN: "Đ.GIÁ",
                            id_ID: "NILAI",
                            ms_MY: "RATING",
                          },
                        },
                        "ui-noads-description": {
                          default: "Disable ads\nand play non-stop!",
                          localizations: {
                            ru_RU: "Отключите рекламу\nи играйте без остановки!",
                            es_ES: "¡Deshabilita los anuncios\ny juega sin interrupciones!",
                            es_LA: "¡Desactiva los anuncios para jugar sin parar!",
                            pt_PT: "Desative anúncios\ne jogue sem interrupções!",
                            pt_BR: "Desativa os anúncios\ne joga sem parar!",
                            zh_CN: "禁用广告\n玩不停！",
                            fr_FR: "Désactiver les annonces\net jouer non-stop",
                            de_DE: "Keine Werbung\nund nonstop spielen!",
                            zh_TW: "去除廣告\n然後暢玩！",
                            ja_JP: "広告を無効にして\nノンストップでプレイ！",
                            ko_KR: "광고를 비활성화하고\n방해 없이 플레이하세요!",
                            it_IT: "Elimina pubblicità\ne interruzioni!",
                            pl_PL: "Wyłącz reklamy\ni graj bez przerwy!",
                            tr_TR: "Reklamları kapat\nve durmaksızın oyna!",
                            th_TH: "ปิดการใช้งานโฆษณา\nและเล่นได้อย่างต่อเนื่อง!",
                            hi_IN: "विज्ञापन अक्षम करें\nऔर बिना रुके खेलें!",
                            vi_VN: "Tắt q.cáo\nvà chơi liên tục!",
                            id_ID: "Matikan iklan\ndan bermain tanpa henti!",
                            ms_MY: "Lumpuhkan iklan\ndan main tanpa henti!",
                          },
                        },
                        "ui-menu-level_num": {
                          default: "LEVEL",
                          localizations: {
                            ru_RU: "УРОВЕНЬ",
                            es_ES: "NIVEL",
                            es_LA: "NIVEL",
                            pt_PT: "NÍVEL",
                            pt_BR: "NÍVEL",
                            zh_CN: "关卡",
                            fr_FR: "NIVEAU",
                            de_DE: "LEVEL",
                            zh_TW: "關卡",
                            ja_JP: "レベル",
                            ko_KR: "레벨",
                            it_IT: "LIVELLO",
                            pl_PL: "POZIOM",
                            tr_TR: "BÖLÜM",
                            th_TH: "ระดับ",
                            hi_IN: "लेवल",
                            vi_VN: "CẤP ĐỘ",
                            id_ID: "LEVEL",
                            ms_MY: "TAHAP",
                          },
                        },
                        "ui-win-claim": {
                          default: "CLAIM",
                          localizations: {
                            ru_RU: "ПОЛУЧИТЬ",
                            es_ES: "SOLICITAR",
                            es_LA: "RECLAMAR",
                            pt_PT: "RESGATAR",
                            pt_BR: "RESGATAR",
                            zh_CN: "领取",
                            fr_FR: "RECEVOIR",
                            de_DE: "ERHALTEN",
                            zh_TW: "領取",
                            ja_JP: "請求する",
                            ko_KR: "획득",
                            it_IT: "RICHIEDI",
                            pl_PL: "ODBIERZ",
                            tr_TR: "AL",
                            th_TH: "รับ",
                            hi_IN: "दावा करें",
                            vi_VN: "NHẬN THƯỞNG",
                            id_ID: "KLAIM",
                            ms_MY: "TUNTUT",
                          },
                        },
                        "ui-try-again-button": {
                          default: "TRY AGAIN",
                          localizations: {
                            ru_RU: "TRY AGAIN",
                            es_ES: "TRY AGAIN",
                            es_LA: "TRY AGAIN",
                            pt_PT: "TRY AGAIN",
                            pt_BR: "TRY AGAIN",
                            zh_CN: "TRY AGAIN",
                            fr_FR: "TRY AGAIN",
                            de_DE: "TRY AGAIN",
                            zh_TW: "TRY AGAIN",
                            ja_JP: "TRY AGAIN",
                            ko_KR: "TRY AGAIN",
                            it_IT: "TRY AGAIN",
                            pl_PL: "TRY AGAIN",
                            tr_TR: "TRY AGAIN",
                            th_TH: "TRY AGAIN",
                            hi_IN: "TRY AGAIN",
                            vi_VN: "TRY AGAIN",
                            id_ID: "TRY AGAIN",
                            ms_MY: "TRY AGAIN",
                          },
                        },
                        "ui-settings-restore_purchase": {
                          default: "RESTORE\nPURCHASES",
                          localizations: {
                            ru_RU: "ВОССТАНОВИТЬ\nПОКУПКИ",
                            es_ES: "RESTAURAR\nCOMPRAS",
                            es_LA: "RESTAURAR\nCOMPRAS",
                            pt_PT: "RESTAURAR\nCOMPRAS",
                            pt_BR: "REPOR\nCOMPRAS",
                            zh_CN: "恢复\n购买",
                            fr_FR: "RESTAURER\nACHATS",
                            de_DE: "EINKÄUFE\nWIEDERHERSTELLEN",
                            zh_TW: "重置\n購買",
                            ja_JP: "購入を\n復元する",
                            ko_KR: "구매\n복구",
                            it_IT: "RIPRIST.\nACQUISTI",
                            pl_PL: "PRZYWRÓĆ\nZAKUPY",
                            tr_TR: "ALIMLARI\nGERİ YÜKLE",
                            th_TH: "กู้คืน\nการซื้อ",
                            hi_IN: "खरीद\nबहाल करें",
                            vi_VN: "KHÔI PHỤC\nMUA HÀNG",
                            id_ID: "PULIHKAN\nPEMBELIAN",
                            ms_MY: "PULIHKAN\nPEMBELIAN",
                          },
                        },
                        "ui-win-continue": {
                          default: "CONTINUE",
                          localizations: {
                            ru_RU: "ПРОДОЛЖИТЬ",
                            es_ES: "CONTINUAR",
                            es_LA: "CONTINUAR",
                            pt_PT: "CONTINUAR",
                            pt_BR: "CONTINUAR",
                            zh_CN: "继续",
                            fr_FR: "CONTINUER",
                            de_DE: "FORTFAHREN",
                            zh_TW: "繼續",
                            ja_JP: "続行",
                            ko_KR: "계속",
                            it_IT: "CONTINUA",
                            pl_PL: "KONTYNUUJ",
                            tr_TR: "DEVAM",
                            th_TH: "ต่อไป",
                            hi_IN: "जारी रखें",
                            vi_VN: "TIẾP TỤC",
                            id_ID: "LANJUTKAN",
                            ms_MY: "TERUSKAN",
                          },
                        },
                        "ui-gdpr-title": {
                          default: "We've updated our Terms",
                          localizations: {
                            ru_RU: "Мы обновили наши условия использования",
                            es_ES: "Hemos actualizado nuestras condiciones de uso.",
                            es_LA: "Actualizamos nuestros términos de servicio.",
                            pt_PT: "Atualizamos nossos termos e condições.",
                            pt_BR:
                              "Atualizámos os nossos termos e condições. Para continuar a jogar, aceita os novos Termos de Utilização.",
                            zh_CN: "当社の利用規約が更新されました。",
                            fr_FR: "Nous avons mis à jour nos conditions générales.",
                            de_DE: "Unsere Nutzungsbedingungen haben sich geändert.",
                            zh_TW: "약관을 업데이트했습니다.",
                            ja_JP: "条款和条件已更新。",
                            ko_KR: "我們更新了我們的合約條款.",
                            it_IT: "Abbiamo aggiornato i nostri termini e condizioni.",
                            pl_PL: "Zaktualizowaliśmy nasze warunki",
                            tr_TR: "Koşullarımız güncellendi.",
                            th_TH: "เราได้อัปเดตข้อกำหนดในการให้บริการเกมแล้ว",
                            hi_IN: "हमने अपनी शर्तों को अपडेट कर दिया है।",
                            vi_VN: "Chúng tôi đã cập nhật các Điều khoản",
                            id_ID: "Kami sudah memperbarui Ketentuan kami",
                            ms_MY: "Kami telah mengemas kini Syarat kami",
                          },
                        },
                        "ui-gdpr-description": {
                          default: 'By tapping "Accept" you agree to them',
                          localizations: {
                            ru_RU: 'Нажимая "Принять", вы соглашаетесь с ними.',
                            es_ES: "Al tocar Aceptar,\nlas aceptas",
                            es_LA: "Al tocar Aceptar,\nlas aceptas",
                            pt_PT: "Ao tocar Aceito,\nvocê os aceita",
                            pt_BR: "Ao tocar em Aceitar,\nconcordas com eles",
                            zh_CN: "要继续玩\n请接受我们的新使用条款。",
                            fr_FR: "En touchant Accepter, vous\nconvenez de les respecter",
                            de_DE: "Wenn du auf Akzeptieren tippst,\nstimmst du ihnen zu",
                            zh_TW: "想繼續遊玩，\n請先接受我們的合約條款。",
                            ja_JP:
                              "承諾をタップすると、利用規約および\nプライバシーポリシーに同意したことになります",
                            ko_KR: "동의를 탭하여\n약관에 동의해 주십시오.",
                            it_IT:
                              "Per continuare a giocare,\naccetta le nostre nuove Condizioni per l'uso.",
                            pl_PL:
                              "Aby dlaej grać,\nmusisz zaakceptować nasz nowy Warunki świadczenia usług.",
                            tr_TR: "Kabul et butonuna basmakla\nbunları kabul etmiş sayılırsınız",
                            th_TH: "เมื่อแตะที่ยอมรับ คุณได้\nยอมรับเงื่อนไขและนโยบายทั้งหมด",
                            hi_IN: '"स्वीकार करें" पर टैप करके आप इन से सहमत हैं',
                            vi_VN:
                              "Để tiếp tục chơi,\nvui lòng chấp nhận Điều khoản sử dụng mới của chúng tôi.",
                            id_ID:
                              "Untuk melanjutkan permainan,\nsetujui Ketentuan Penggunaan baru kami.",
                            ms_MY: 'Dengan mengetik "Terima"\nanda bersetuju dengan mereka',
                          },
                        },
                        "ui-gdpr-accept_button": {
                          default: "ACCEPT",
                          localizations: {
                            ru_RU: "ПРИНЯТЬ",
                            es_ES: "Acceptar",
                            es_LA: "ACEPTAR",
                            pt_PT: "Aceitar",
                            pt_BR: "Aceitar",
                            zh_CN: "接受",
                            fr_FR: "Accepter",
                            de_DE: "Akzeptieren",
                            zh_TW: "同意",
                            ja_JP: "承諾する",
                            ko_KR: "수락",
                            it_IT: "Accetta",
                            pl_PL: "Akceptuj",
                            tr_TR: "Kabul et",
                            th_TH: "ยอมรับ",
                            hi_IN: "स्वीकार करें",
                            vi_VN: "Chấp nhận",
                            id_ID: "Terima",
                            ms_MY: "Terima",
                          },
                        },
                        "ui-gdpr-terms_button": {
                          default: "Terms Of Service",
                          localizations: {
                            ru_RU: "Условия использования",
                            es_ES: "Condiciones de uso",
                            es_LA: "Términos de servicio",
                            pt_PT: "Termos de Uso",
                            pt_BR: "Termos de Utilização",
                            zh_CN: "利用規約",
                            fr_FR: "Conditions d'utilisation",
                            de_DE: "Nutzungsbedingungen",
                            zh_TW: "使用條款",
                            ja_JP: "使用条款",
                            ko_KR: "사용 약관",
                            it_IT: "Condizioni di utilizzo",
                            pl_PL: "Warunki świadczenia usług",
                            tr_TR: "Hizmet Koşulları",
                            th_TH: "ข้อกำหนดในการให้บริการ",
                            hi_IN: "सेवा की शर्तें",
                            vi_VN: "Điều khoản dịch vụ",
                            id_ID: "Ketentuan Penggunaan",
                            ms_MY: "Syarat Perkhidmatan",
                          },
                        },
                        "ui-gdpr-privacy_button": {
                          default: "Privacy Policy",
                          localizations: {
                            ru_RU: "Политика конфиденциальности",
                            es_ES: "Política de privacidad",
                            es_LA: "Política de privacidad",
                            pt_PT: "Política de Privacidade",
                            pt_BR: "Política de Privacidade",
                            zh_CN: "隐私政策",
                            fr_FR: "Charte de confidentialité",
                            de_DE: "Datenschutzerklärung",
                            zh_TW: "隱私政策",
                            ja_JP: "プライバシーポリシー",
                            ko_KR: "개인정보 보호정책",
                            it_IT: "Informativa sulla privacy",
                            pl_PL: "Polityka prywatności",
                            tr_TR: "Gizlilik politikası",
                            th_TH: "นโยบายความเป็นส่วนตัว",
                            hi_IN: "गोपनीयता नीति",
                            vi_VN: "Chính sách bảo mật",
                            id_ID: "Kebijakan Privasi",
                            ms_MY: "Dasar Privasi",
                          },
                        },
                        "ui-offline-title": {
                          default: "OFFLINE EARNINGS",
                          localizations: {
                            ru_RU: "ОФФЛАЙН ДОХОД",
                            es_ES: "GANANCIAS AUSENTE",
                            es_LA: "GANANCIAS AUSENTE",
                            pt_PT: "GANHOS OFFLINE",
                            pt_BR: "GANHOS OFFLINE",
                            zh_CN: "离线收益",
                            fr_FR: "GAINS HORS LIGNE",
                            de_DE: "OFFLINE-ERLÖSE",
                            zh_TW: "離線收入",
                            ja_JP: "オフラインでの得点",
                            ko_KR: "오프라인 수익",
                            it_IT: "GUADAGNI OFFLINE",
                            pl_PL: "ZAROBKI OFFLINE",
                            tr_TR: "ÇEVRİMDIŞI KAZANÇ",
                            th_TH: "รายได้แบบออฟไลน์",
                            hi_IN: "ऑफलाइन कमाई",
                            vi_VN: "THU NHẬP NG.TUYẾN",
                            id_ID: "PENDAPATAN OFFLINE",
                            ms_MY: "HASIL LUAR TALIAN",
                          },
                        },
                        "ui-offline-description": {
                          default: "YOU WERE AWAY FOR:",
                          localizations: {
                            ru_RU: "ВАС НЕ БЫЛО:",
                            es_ES: "HAS ESTADO SIN JUGAR:",
                            es_LA: "ESTUVISTE AUSENTE POR:",
                            pt_PT: "ESTIVESTE AUSENTE DURANTE:",
                            pt_BR: "ESTIVESTE AUSENTE DURANTE:",
                            zh_CN: "你离开了：",
                            fr_FR: "VOUS ÊTES PARTI PENDANT :",
                            de_DE: "DU WARST WEG FÜR:",
                            zh_TW: "你共離開了：",
                            ja_JP: "離れていた時間：",
                            ko_KR: "你共離開了：",
                            it_IT: "NON GIOCHI DA:",
                            pl_PL: "NIE BYŁO CIĘ PRZEZ:",
                            tr_TR: "SEN YOKKEN GEÇEN ZAMAN:",
                            th_TH: "คุณหายไปเป็นเวลา:",
                            hi_IN: "आप इतने समय से दूर थे",
                            vi_VN: "BẠN ĐÃ VẮNG MẶT TRONG:",
                            id_ID: "KAMU PERGI SELAMA:",
                            ms_MY: "ANDA JAUH DARI PERMAINAN SELAMA:",
                          },
                        },
                        "ui-offline-mult_button": {
                          default: "MULTIPLY",
                          localizations: {
                            ru_RU: "УМНОЖИТЬ",
                            es_ES: "MULTIPLICAR",
                            es_LA: "MULTIPLICAR",
                            pt_PT: "MULTIPLICAR",
                            pt_BR: "MULTIPLICAR",
                            zh_CN: "翻倍",
                            fr_FR: "MULTIPLIER",
                            de_DE: "MULTIPLIZIEREN",
                            zh_TW: "翻倍",
                            ja_JP: "マルチプレイ",
                            ko_KR: "멀티플레이",
                            it_IT: "MOLTIPLICA",
                            pl_PL: "POMNÓŻ",
                            tr_TR: "KATLA",
                            th_TH: "คูณ",
                            hi_IN: "मल्टीप्लाई",
                            vi_VN: "NHÂN",
                            id_ID: "LIPAT GANDA",
                            ms_MY: "PELBAGAI",
                          },
                        },
                        "ui-menu-capturing": {
                          default: "CAPTURING",
                          localizations: {
                            ru_RU: "ЗАХВАТ",
                            es_ES: "CAPTURAR",
                            es_LA: "CAPTURAR",
                            pt_PT: "CAPTURA",
                            pt_BR: "A CAPTURAR",
                            zh_CN: "抓住",
                            fr_FR: "CAPTURE",
                            de_DE: "WIRD GEFANGEN",
                            zh_TW: "抓住",
                            ja_JP: "征服中",
                            ko_KR: "캡처",
                            it_IT: "IN CATTURA",
                            pl_PL: "PRZEJMOWANIE",
                            tr_TR: "YAKALAMA",
                            th_TH: "กำลังยึด",
                            hi_IN: "कब्जा करना",
                            vi_VN: "CHIẾM",
                            id_ID: "MENANGKAP",
                            ms_MY: "MENGHASILKAN",
                          },
                        },
                        "ui-fillbox-get": {
                          default: "GET",
                          localizations: {
                            ru_RU: "ПОЛУЧИТЬ",
                            es_ES: "OBTENER",
                            es_LA: "OBTENER",
                            pt_PT: "GAHNE",
                            pt_BR: "OBTER",
                            zh_CN: "获取",
                            fr_FR: "OBTENIR",
                            de_DE: "NIMM",
                            zh_TW: "獲取",
                            ja_JP: "ゲット",
                            ko_KR: "ゲット",
                            it_IT: "OTTIENI",
                            pl_PL: "WEŹ",
                            tr_TR: "AL",
                            th_TH: "รับ",
                            hi_IN: "प्राप्त करें",
                            vi_VN: "LẤY",
                            id_ID: "DAPATKAN",
                            ms_MY: "DAPATKAN",
                          },
                        },
                        "ui-upgrade-units": {
                          default: "units",
                          localizations: {
                            ru_RU: "юниты",
                            es_ES: "tropas",
                            es_LA: "tropas",
                            pt_PT: "uni.",
                            pt_BR: "uni.",
                            zh_CN: "单位",
                            fr_FR: "unités",
                            de_DE: "Einh.",
                            zh_TW: "單位",
                            ja_JP: "部隊",
                            ko_KR: "유닛",
                            it_IT: "unità",
                            pl_PL: "jedn.",
                            tr_TR: "Birim",
                            th_TH: "หน่วย",
                            hi_IN: "यूनिट",
                            vi_VN: "đơn vị",
                            id_ID: "unit",
                            ms_MY: "unit",
                          },
                        },
                        "ui-upgrate-rate": {
                          default: "units per second",
                          localizations: {
                            ru_RU: "юниты в секунду",
                            es_ES: "tropas por segundo",
                            es_LA: "tropas por segundo",
                            pt_PT: "unidades por segundo",
                            pt_BR: "uni. por segundo",
                            zh_CN: "每秒单位",
                            fr_FR: "unités par seconde",
                            de_DE: "Einheiten/s",
                            zh_TW: "每秒單位",
                            ja_JP: "1秒毎の部隊",
                            ko_KR: "1초당 유닛",
                            it_IT: "unità al secondo",
                            pl_PL: "jednostek na sek.",
                            tr_TR: "Birim/sn",
                            th_TH: "หน่วยต่อวินาที",
                            hi_IN: "यूनिट प्रति सेकंड",
                            vi_VN: "đơn vị mỗi giây",
                            id_ID: "unit per detik",
                            ms_MY: "unit sesaat",
                          },
                        },
                        "ui-upgrade-offline": {
                          default: "coins per hour",
                          localizations: {
                            ru_RU: "монет в час",
                            es_ES: "dinero por hora",
                            es_LA: "monedas por hora",
                            pt_PT: "moedas por hora",
                            pt_BR: "moedas por hora",
                            zh_CN: "每小时金币",
                            fr_FR: "pièces par heure",
                            de_DE: "Münzen/h",
                            zh_TW: "每小時硬幣",
                            ja_JP: "1時間毎のコイン",
                            ko_KR: "1시간당 코인",
                            it_IT: "monete all'ora",
                            pl_PL: "monet na godz.",
                            tr_TR: "Jeton/sa",
                            th_TH: "เหรียญต่อชั่วโมง",
                            hi_IN: "सिक्के प्रति घंटा",
                            vi_VN: "xu mỗi giờ",
                            id_ID: "koin per jam",
                            ms_MY: "syiling sejam",
                          },
                        },
                        "ui-common-free": {
                          default: "FREE",
                          localizations: {
                            ru_RU: "БЕСПЛАТНО",
                            es_ES: "GRATIS",
                            es_LA: "GRATIS",
                            pt_PT: "GRÁTIS",
                            pt_BR: "GRÁTIS",
                            zh_CN: "免费",
                            fr_FR: "GRATUIT",
                            de_DE: "KOSTENLOS",
                            zh_TW: "免費",
                            ja_JP: "無料",
                            ko_KR: "무료",
                            it_IT: "GRATIS",
                            pl_PL: "DARMOWE",
                            tr_TR: "BEDAVA",
                            th_TH: "ฟรี",
                            hi_IN: "मुफ्त",
                            vi_VN: "MIỄN PHÍ",
                            id_ID: "GRATIS",
                            ms_MY: "PERCUMA",
                          },
                        },
                        "ui-fillbox-new_skin": {
                          default: "NEW SKIN",
                          localizations: {
                            ru_RU: "НОВЫЙ СКИН",
                            es_ES: "NUEVO ASPECTO",
                            es_LA: "NUEVA SKIN",
                            pt_PT: "NOVO VISUAL",
                            pt_BR: "NOVO VISUAL",
                            zh_CN: "新皮肤",
                            fr_FR: "NOUVELLE APPARENCE",
                            de_DE: "NEUER SKIN",
                            zh_TW: "新造型",
                            ja_JP: "新スキン",
                            ko_KR: "신규 스킨",
                            it_IT: "NUOVA SKIN",
                            pl_PL: "NOWA SKÓRKA",
                            tr_TR: "YENI GÖRÜNÜM",
                            th_TH: "สกินใหม่",
                            hi_IN: "नई स्किन",
                            vi_VN: "DIỆN MẠO MỚI",
                            id_ID: "SKIN BARU",
                            ms_MY: "KULIT BAHARU",
                          },
                        },
                        "ui-fillbox-use": {
                          default: "USE",
                          localizations: {
                            ru_RU: "ИСПОЛЬЗОВАТЬ",
                            es_ES: "USAR",
                            es_LA: "USAR",
                            pt_PT: "USAR",
                            pt_BR: "USAR",
                            zh_CN: "使用",
                            fr_FR: "UTILISER",
                            de_DE: "VERWENDEN",
                            zh_TW: "使用",
                            ja_JP: "使用",
                            ko_KR: "사용",
                            it_IT: "USA",
                            pl_PL: "UŻYJ",
                            tr_TR: "KULLAN",
                            th_TH: "ใช้",
                            hi_IN: "उपयोग करें",
                            vi_VN: "DÙNG",
                            id_ID: "GUNAKAN",
                            ms_MY: "GUNAKAN",
                          },
                        },
                        "ui-fillbox-no_content": {
                          default: "New content coming soon...",
                          localizations: {
                            ru_RU: "Новый контент уже на подходе...",
                            es_ES: "Nuevo contenido próximamente...",
                            es_LA: "Nuevo contenido pronto",
                            pt_PT: "Novo conteúdo em breve...",
                            pt_BR: "Mais conteúdo em breve...",
                            zh_CN: "新内容即将发布……",
                            fr_FR: "Nouveaux contenus prochainement...",
                            de_DE: "Neuer Inhalt in Kürze …",
                            zh_TW: "新內容即將發布……",
                            ja_JP: "新コンテンツが間もなく登場…",
                            ko_KR: "신규 콘텐츠가 곧 출시됩니다…",
                            it_IT: "Nuovi contenuti presto in arrivo…",
                            pl_PL: "Nowa zawartość pojawi się wkrótce…",
                            tr_TR: "Yeni içerik yakında geliyor…",
                            th_TH: "คอนเทนต์ใหม่จะมาถึงเร็วๆ นี้...",
                            hi_IN: "नई सामग्री जल्द आ रही है...",
                            vi_VN: "Sắp có nội dung mới…",
                            id_ID: "Konten baru segera hadir…",
                            ms_MY: "Kandungan baharu tidak lama lagi...",
                          },
                        },
                        "ui-fillbox-title": {
                          default: "GIFT",
                          localizations: {
                            ru_RU: "ПОДАРОК",
                            es_ES: "REGALO",
                            es_LA: "REGALO",
                            pt_PT: "PRENDA",
                            pt_BR: "PRENDA",
                            zh_CN: "礼物",
                            fr_FR: "CADEAU",
                            de_DE: "GESCHENK",
                            zh_TW: "禮物",
                            ja_JP: "プレゼント",
                            ko_KR: "선물",
                            it_IT: "REGALO",
                            pl_PL: "PREZENT",
                            tr_TR: "HEDİYE",
                            th_TH: "ของขวัญ",
                            hi_IN: "GIFT",
                            vi_VN: "MÓN QUÀ",
                            id_ID: "HADIAH",
                            ms_MY: "{0} KIRI MUSUH",
                          },
                        },
                        "ui-gameplay-players_left": {
                          default: "{0} ENEMY LEFT",
                          localizations: {
                            ru_RU: "{0} ВРАГОВ ОСТАЛОСЬ",
                            es_ES: "QUEDA(N) {0} ENEMIGO(S)",
                            es_LA: "QUEDA(N) {0} ENEMIGO(S)",
                            pt_PT: "{0} INIMIGO(S) RESTANTE(S)",
                            pt_BR: "{0} INIMIGO(S) RESTANTE(S)",
                            zh_CN: "剩余{0}个敌人",
                            fr_FR: "{0} ENNEMI RESTANT",
                            de_DE: "NOCH {0} GEGNER",
                            zh_TW: "剩餘 {0} 個敵人",
                            ja_JP: "敵残り{0}",
                            ko_KR: "적 {0}명 남음",
                            it_IT: "NEMICI RIMASTI: {0}",
                            pl_PL: "POZOSTAŁYCH WROGÓW: {0}",
                            tr_TR: "{0} DÜŞMAN KALDI",
                            th_TH: "เหลือศัตรูอีก {0}",
                            hi_IN: "{0} दुश्मन शेष",
                            vi_VN: "{0} KẺ THÙ CÒN LẠI",
                            id_ID: "{0} MUSUH TERSISA",
                            ms_MY: "{0} MUSUH TINGGAL",
                          },
                        },
                        "ui-menu-hint": {
                          default: "HINT: YOU CAN ALSO CHANGE IT LATER",
                          localizations: {
                            ru_RU: "ПОДСКАЗКА: ВЫ МОЖЕТЕ ИЗМЕНИТЬ ЦВЕТ ПОЗЖЕ",
                            es_ES: "PISTA: PUEDES CAMBIAR EL COLOR MÁS TARDE",
                            es_LA: "PISTA: LUEGO PODRÁS CAMBIAR DE COLOR",
                            pt_PT: "DICA: É POSSÍVEL ALTERAR A COR DEPOIS",
                            pt_BR: "DICA: PODES MUDAR A COR MAIS TARDE",
                            zh_CN: "提示：你也可以在稍后更换颜色",
                            fr_FR: "ASTUCE : VOUS POUVEZ AUSSI CHANGER DE COULEUR PLUS TARD",
                            de_DE: "TIPP: FARBEN KANNST DU AUCH SPÄTER ÄNDERN",
                            zh_TW: "提示：你也可以在稍後更換顏色",
                            ja_JP: "ヒント: 色は後から変更することができる",
                            ko_KR: "힌트: 추후 색상을 변경할 수 있습니다",
                            it_IT: "SUGGERIMENTO: PUOI ANCHE CAMBIARE COLORE PIÙ TARDI",
                            pl_PL: "WSKAZÓWKA: MOŻESZ TEŻ ZMIENIĆ KOLOR PÓŹNIEJ",
                            tr_TR: "İPUCU: RENGİ SONRA DA DEĞİŞTİREBİLİRSİN",
                            th_TH: "คำแนะนำ: คุณสามารถเปลี่ยนสีได้ภายหลัง",
                            hi_IN: "संकेत: आप बाद में भी रंग बदल सकते हैं",
                            vi_VN: "GỢI Ý: BẠN CŨNG CÓ THỂ THAY ĐỔI MÀU SẮC SAU NÀY",
                            id_ID: "PETUNJUK: KAMU JUGA BISA MENGUBAH WARNA NANTI",
                            ms_MY: "PETUA: ANDA JUGA BOLEH MENUKAR WARNA KEMUDIAN",
                          },
                        },
                        "ui-upgrade-start_units": {
                          default: "START UNITS",
                          localizations: {
                            ru_RU: "СТАРТОВЫЕ ЮНИТЫ",
                            es_ES: "TROPAS INICIO",
                            es_LA: "TROPAS INICIO",
                            pt_PT: "UN. INICIAIS",
                            pt_BR: "UNI. INICIAIS",
                            zh_CN: "开始单位",
                            fr_FR: "UNITÉS INIT.",
                            de_DE: "STARTEINH.",
                            zh_TW: "開始單位",
                            ja_JP: "開始ユニット",
                            ko_KR: "시작 유닛",
                            it_IT: "UNITÀ INIZ.",
                            pl_PL: "JDN. STARTOWE",
                            tr_TR: "BAŞLANGIÇ BİRİMİ",
                            th_TH: "หน่วยเริ่มต้น",
                            hi_IN: "यूनिट शुरू करें",
                            vi_VN: "Đ.VỊ KHỞI ĐẦU",
                            id_ID: "MULAI UNIT",
                            ms_MY: "MULA UNIT",
                          },
                        },
                        "ui-upgrade-produce_speed": {
                          default: "PRODUCE SPEED",
                          localizations: {
                            ru_RU: "СКОРОСТЬ ПРОИЗВОДСТВА",
                            es_ES: "VELOC. PRODUCC.",
                            es_LA: "VELOC. PRODUCC.",
                            pt_PT: "VEL. DE PROD.",
                            pt_BR: "VEL. PRODUÇÃO",
                            zh_CN: "生产速度",
                            fr_FR: "VIT. PRODUCTION",
                            de_DE: "ERTRAGSTEMPO",
                            zh_TW: "生產速度",
                            ja_JP: "生産速度",
                            ko_KR: "생산 속도",
                            it_IT: "VELOCITÀ PRODUZ",
                            pl_PL: "SZYBKOŚĆ PROD.",
                            tr_TR: "ÜRETİM HIZI",
                            th_TH: "ความเร็วการผลิต",
                            hi_IN: "गति उत्पन्न करें",
                            vi_VN: "TỐC ĐỘ SẢN XUẤT",
                            id_ID: "MEMBUAT KEC.",
                            ms_MY: "HASIL LAJU",
                          },
                        },
                        "ui-loading-label": {
                          default: "LOADING",
                          localizations: {
                            ru_RU: "ЗАГРУЗКА",
                            es_ES: "CARGANDO",
                            es_LA: "CARGANDO",
                            pt_PT: "CARREGANDO",
                            pt_BR: "A CARREGAR",
                            zh_CN: "正在加载",
                            fr_FR: "CHARGEMENT",
                            de_DE: "LADEN",
                            zh_TW: "讀取中",
                            ja_JP: "読み込み中",
                            ko_KR: "로딩중",
                            it_IT: "CARICAMENTO",
                            pl_PL: "ŁADOWANIE",
                            tr_TR: "YÜKLENIYOR",
                            th_TH: "กำลังโหลด",
                            hi_IN: "लोड हो रहा है",
                            vi_VN: "ĐANG TẢI",
                            id_ID: "MEMUAT",
                            ms_MY: "MENGHASILKAN KELAJUAN",
                          },
                        },
                        "ui-menu-lvl": {
                          default: "LVL",
                          localizations: {
                            ru_RU: "УР.",
                            es_ES: "NIVEL",
                            es_LA: "NIVEL",
                            pt_PT: "NV",
                            pt_BR: "NVL",
                            zh_CN: "等级",
                            fr_FR: "NV",
                            de_DE: "LVL",
                            zh_TW: "等級",
                            ja_JP: "位",
                            ko_KR: "등급",
                            it_IT: "LIV.",
                            pl_PL: "POZ",
                            tr_TR: "SV",
                            th_TH: "เลเวล",
                            hi_IN: "स्तर",
                            vi_VN: "CẤP",
                            id_ID: "LVL",
                            ms_MY: "THP",
                          },
                        },
                        game_invite: {
                          default: "Invite",
                          localizations: {
                            ru_RU: "Пригласить",
                            es_ES: "Invitar",
                            es_LA: "Invitar",
                            pt_PT: "Convidar",
                            pt_BR: "Convidar",
                            fr_FR: "Inviter",
                            de_DE: "Einladen",
                            zh_CN: "邀请",
                            zh_TW: "邀請",
                            ja_JP: "招待",
                            ko_KR: "초대",
                            it_IT: "Invita",
                            pl_PL: "Zaproś",
                            tr_TR: "Davet et",
                            th_TH: "ชวนเพื่อน",
                            hi_IN: "आमंत्रित करें",
                            vi_VN: "Mời",
                            id_ID: "Undang",
                            ms_MY: "Jemput",
                          },
                        },
                        game_pending_description: {
                          default: "The reward is given when your friend launch the game",
                          localizations: {
                            ru_RU: "Награда выдается, когда ваш друг запускает игру",
                          },
                        },
                        game_pending: {
                          default: "Pending...",
                          localizations: {
                            ru_RU: "Ожидание...",
                            es_ES: "Cargando…",
                            es_LA: "Cargando...",
                            pt_PT: "Carregando...",
                            pt_BR: "A carregar...",
                            fr_FR: "Chargement...",
                            de_DE: "Laden...",
                            zh_CN: "加载...",
                            zh_TW: "載入中……",
                            ja_JP: "読み込み中...",
                            ko_KR: "로딩...",
                            it_IT: "Caricamento...",
                            pl_PL: "Ładowanie...",
                            tr_TR: "Yükleniyor...",
                            th_TH: "กำลังโหลด...",
                            hi_IN: "लोड हो रहा है..",
                            vi_VN: "Đang tải...",
                            id_ID: "Memuat...",
                            ms_MY: "Memuatkan…",
                          },
                        },
                        tap_to_play_go: { default: "GO!", localizations: {} },
                        level_completed_message: {
                          default: "ALL STAGES COMPLETED!",
                          localizations: {
                            ru_RU: "Уровни пройдены!",
                            es_ES: "ALL STAGES COMPLETED!",
                            es_LA: "ALL STAGES COMPLETED!",
                            pt_PT: "ALL STAGES COMPLETED!",
                            pt_BR: "ALL STAGES COMPLETED!",
                            fr_FR: "ALL STAGES COMPLETED!",
                            de_DE: "ALL STAGES COMPLETED!",
                            zh_CN: "ALL STAGES COMPLETED!",
                            zh_TW: "ALL STAGES COMPLETED!",
                            ja_JP: "ALL STAGES COMPLETED!",
                            ko_KR: "ALL STAGES COMPLETED!",
                            it_IT: "ALL STAGES COMPLETED!",
                            pl_PL: "ALL STAGES COMPLETED!",
                            tr_TR: "ALL STAGES COMPLETED!",
                            th_TH: "ALL STAGES COMPLETED!",
                            hi_IN: "ALL STAGES COMPLETED!",
                            vi_VN: "ALL STAGES COMPLETED!",
                            id_ID: "ALL STAGES COMPLETED!",
                            ms_MY: "ALL STAGES COMPLETED!",
                          },
                        },
                        game_login_btn: {
                          default: "Login",
                          localizations: { ru_RU: "Авторизация" },
                        },
                        game_login_text: {
                          default: "Log in to compete with others and guaranteed to save progress.",
                          localizations: {
                            ru_RU:
                              "Авторизуйтесь для соревнования с другими и гарантированного сохранение прогресса.",
                          },
                        },
                      },
                      sid: "191972",
                      firebase: {
                        apiKey: "AIzaSyC-94MTsqmwJc1UaOjaJ3-FHxVDBVff5X4",
                        authDomain: "state-io-instant.firebaseapp.com",
                        databaseURL: "https://state-io-instant-default-rtdb.firebaseio.com",
                        projectId: "state-io-instant",
                        storageBucket: "state-io-instant.appspot.com",
                        messagingSenderId: "231713697317",
                        appId: "1:231713697317:web:6bea8945b5b7ece78719cc",
                        measurementId: "G-BPTQG2XDY5",
                      },
                      version: "0.0.63",
                    }) && u.di.rebind(o.TypesCore.gameConfig).toConstantValue(d),
                    null == (h = (0, u.lazyGet)(o.TypesAnalytics.tracker)) ||
                      h.addProvider(new r.GTAGAnalyticsProvider()),
                    (p = u.di.get(o.TypesCore.gameConfig)),
                    (0, u.lazyRun)("template.action"),
                    (f = p.i18n) && s.Localize.addTemplates(f),
                    [
                      4,
                      Promise.all([
                        this.page.isBusReadyAsync().then(function () {
                          _ = (0, u.lazyRun)(o.TypesApp.loginAction)
                        }),
                        (0, u.lazyRun)(o.TypesFlow.assetsPreload),
                      ]),
                    ]
                  )
                case 1:
                  return (
                    i.sent(),
                    (this.page.assetsProgress = 1),
                    a.log.trace("all done"),
                    [4, this.social.startGameAsync()]
                  )
                case 2:
                  return (
                    i.sent(),
                    (0, u.lazyRun)(o.TypesAudio.initAction),
                    [4, (0, u.lazyRun)(o.TypesFlow.UI.setupAction)]
                  )
                case 3:
                  return (
                    i.sent(),
                    Promise.all(
                      [o.TypesFlow.assetsProcess, o.TypesAds.initAction].map(u.lazyRun),
                    ).then(),
                    [
                      4,
                      this.social.init(
                        null === (e = this.page.bus) || void 0 === e ? void 0 : e.params,
                      ),
                    ]
                  )
                case 4:
                  return (
                    i.sent(),
                    (function () {
                      var e = g.social.me,
                        t = e.id,
                        n = e.name,
                        i = e.photo
                      c.setUser({ id: t, name: n, photo: i, locale: s.Localize.defaultLocale })
                    })(),
                    null === (t = (0, u.lazyGet)(o.TypesSocial.refRewardsModel)) ||
                      void 0 === t ||
                      t.init(),
                    [4, _]
                  )
                case 5:
                  return (
                    i.sent(),
                    (l.AdManagerBase.config.throttling.interstitial.systemStart = Date.now()),
                    [4, (0, u.lazyRun)(o.TypesFlow.mainAction)]
                  )
                case 6:
                  return (
                    i.sent(),
                    [
                      4,
                      null === (n = (0, u.lazyGet)(o.TypesAudio.model)) || void 0 === n
                        ? void 0
                        : n.activateBackgroundMusic(),
                    ]
                  )
                case 7:
                  return (i.sent(), [2])
              }
            })
          })
        }),
        i.__decorate(
          [(0, d.inject)(o.TypesApp.pageModel), i.__metadata("design:type", l.PageModel)],
          t.prototype,
          "page",
          void 0,
        ),
        i.__decorate(
          [(0, d.inject)(o.TypesSocial.model), i.__metadata("design:type", Object)],
          t.prototype,
          "social",
          void 0,
        ),
        (t = i.__decorate([(0, d.injectable)()], t))
      )
    })(u.Action)
  t.BootAction = h
}
